# Generated by Django 3.2.8 on 2021-12-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='place_name',
            field=models.TextField(blank=True, null=True, verbose_name='Название места'),
        ),
    ]
