# Generated by Django 3.2.9 on 2021-12-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20211213_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postgallery',
            options={'verbose_name': 'Картинка поста', 'verbose_name_plural': 'Картинки поста'},
        ),
        migrations.RemoveField(
            model_name='postgallery',
            name='product',
        ),
        migrations.AddField(
            model_name='post',
            name='gallery',
            field=models.ManyToManyField(to='MainApp.PostGallery', verbose_name='Картинки поста'),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='img',
            field=models.ImageField(null=True, upload_to='posts/%Y/%m/%d', verbose_name='Картинка поста'),
        ),
    ]
