# Generated by Django 3.2.9 on 2021-12-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20211213_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgallery',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d', verbose_name='Картинка поста'),
        ),
    ]
